#!/opt/homebrew/bin/bash
./configure --host="$TRIPLE" --prefix="$PREFIX" \
            --disable-{doc,tools,maintainer-mode,cxx,hardware-acceleration,tls13-interop,padlock,{ssl2,dtls-srtp}-support,{srp,psk,anon}-authentication,gost,ocsp,nls,rpath,libdane,guile} \
            --with-{included-{libtasn1,unistring},nettle-mini} \
            --without-{idn,p11-kit,tpm{,2},zlib,brotli,zstd}
gmake "-j$JOBS"
gmake install
